#!/usr/bin/env bash
# Create PID file and handle signals

echo $$ > /tmp/myscript.pid

trap 'echo "Y U no love me?!";' SIGINT
trap 'echo "I hate the kill command"; rm -f /tmp/myscript.pid; exit' SIGTERM
trap 'rm -f /tmp/myscript.pid; exit' SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
